### PR TITLE
Remove Agate/Data

### PR DESCRIPTION
**Pull request by sammorrisdesign-zz**
This is part of the work to remove Agate from the frontend project.

### CODE REVIEW

**Comment by sammorrisdesign-zz** [comment]
Anyone?

**Comment by austinh7** [comment]
Just got to this as I was going to use data as it's still showing in the https://github.com/guardian/guss-typography/blob/master/font-scale.png file.

:+1:  if it updates that graphic as well.

**Comment by kaelig** [comment]
Just jumping in before a potential bad merge: you also need to remove all the occurrences of data in the table body.

**Comment by sammorrisdesign** [comment]
[Looks like](https://github.com/guardian/frontend/search?utf8=%E2%9C%93&q=fs-data&type=Code) a few cases of `fs-data` have snuck back in. Is this what you're referring to @kaelig ?

**Comment by kaelig** [comment]
:crocodile:

**Comment by davidrapson** [comment]
Anyone able to provide some context on this? We use Agate/Data a fair bit on Membership; I'm guessing this will eventually get merged so will affect us downstream.

**Comment by kaelig** [comment]
Can somebody please close this? (I'm looking to clean up my unresolved GitHub issues panel :p)

**Pull request closed without merging**
